version: '3.9'
services:
  db:
    container_name: posts_db
    image: mysql:8.0.23
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_USERNAME: 'user'
      MYSQL_ROOT_PASSWORD: 'password'

networks:
  default:
    name: posts_net